# Generated by Django 4.0.3 on 2022-04-06 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familias_coder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='nombre',
            new_name='name',
        ),
    ]
